# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
