# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-13 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_example', '0002_collage_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collage',
            table='collage',
        ),
    ]
